import './globals.css'
import "react-multi-carousel/lib/styles.css";
import { Inter,Roboto } from 'next/font/google'
import TheHeader from '@components/TheHeader'
import  TheFooter  from '@components/TheFooter'
import TopBar from '@components/TopBar';
const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  weight:['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.variable} suppressHydrationWarning={true} >
        <TopBar/>       
        <TheHeader />
        {children}
        <TheFooter />       
      </body>
    </html>
  )
}
